version: 2
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: circleci/python:3.7.6
    steps:
    - checkout
    - restore_cache:
        keys:
        - 3.7-{{ checksum "requirements.txt" }}
    - run:
        name: Install dependencies
        command: |
          python3 -m venv venv
          . venv/bin/activate
          pip install -r requirements.txt
    - save_cache:
        paths:
          - ./venv
        key: 3.7-{{ checksum "requirements.txt" }}
    - run:
        name: Test (pytest)
        command: |
          . venv/bin/activate
          pytest -vv --cov-report term-missing --no-cov-on-fail --cov=src/ src
    - store_artifacts:
        path: .coverage
        destination: .coverage
    - run:
        name: Linter (pylint)
        command: |
          . venv/bin/activate
          pylint src --ignore-patterns=test
    - run:
        name: Formatter (black)
        command: |
          . venv/bin/activate
          black . --check
